### PR TITLE
Organisation descendants

### PR DESCRIPTION
**Pull request by martinfilliau**
WIP

e.g. show all events in the Medical Science Division (i.e. all suburbanisation of the MSD).

### CODE REVIEW

**Comment by martinfilliau** [comment]
More work needs to be done on treating/caching the response from the web service and then do the appropriate query; estimation: 2-4 hours.

**Comment by ahaith** [comment]
@envycontent. This feature is working now.
One last detail to check: At the moment it _always_ includes sub-departments in the search. Is this desired, or should there be a parameter in the url (and if so should it default to True of False)?

**Comment by envycontent** [comment]
For the search on the web interface I think all descendants would be ideal. For the API is there a boolean parameter for including subunits - thought I saw it in the documentation?

**Comment by ahaith** [comment]
It was added to the documentation in anticipation of adding this feature. It's not yet hooked up like that, but wouldn't take long.

N.B. At present this work is only for the API search interface. The web-search won't return results based on sub-organisation, and I'm not sure how that could easily be done. The department view, however, does list all talks taking place for a department eg:
https://talks-dev.oucs.ox.ac.uk/talks/department/id/oxpoints:23233560

I've deployed this branch to staging now, so you can take a look and let me know if there are any further changes needed.

**Comment by envycontent** [comment]
Ah magic. I didn't know about the department view - I suppose there isn't an obvious way to get to it at the moment (something for Phase 2).  I've been meaning to try the API and integrate with my old CMS, so I'll test this out, probably first thing tomorrow.

**Pull request merged**
